language: c

sudo: false

env:
  global:
    - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
    - PIP_DEPENDENCIES="codecov"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

    # Make sure pytest-arraydiff wasn't installed by conda
    - conda remove pytest-arraydiff --force || true

    # Need to use develop instead of install to make sure coverage works
    - pip install -e .

script:
   - python -c 'import pytest_arraydiff.plugin'
   - pytest -vv --arraydiff --cov pytest_arraydiff tests
   - pytest -vv --cov pytest_arraydiff --cov-append tests
   - python setup.py check --restructuredtext

after_success:
   - codecov
